// demos/vue-demo/src/components/Player.vue
<template>
  <div class="player-box">
    <div>
      <div id="video-container" style="height: 400px"></div>
      <div style="display: flex; justify-content: center;">
        <div style="width: 500px; display: flex; flex-direction: column;">
          <div style="display: flex;">url: <input placeholder="url" :value="url" style="width: 450px;" @input="event => url = event.target.value"/></div>
          <div style="display: flex;">accessToken: <input placeholder="accessToken" :value="accessToken" style="width: 450px;" @input="event => accessToken = event.target.value"/></div>
          <div style="display: flex;">template: <input placeholder="template" :value="template" style="width: 450px;" @input="event => template = event.target.value"/></div>
          <div style="display: flex;">width: <input placeholder="width" :value="width" style="width: 450px;" @input="event => width = event.target.value"/></div>
          <div style="display: flex;">height: <input placeholder="height" :value="height" style="width: 450px;" @input="event => height = event.target.value"/></div>
          <div style="display: flex;">staticPath: <input placeholder="staticPath" :value="staticPath" style="width: 450px;" @input="event => staticPath = event.target.value"/></div>
        </div>
      </div>
    </div>
    <div>
      <button v-on:click="init">init</button>
      <button v-on:click="stop">stop</button>
      <button v-on:click="play">play</button>
      <button v-on:click="openSound">openSound</button>
      <button v-on:click="closeSound">closeSound</button>
      <button v-on:click="startSave">startSave</button>
      <button v-on:click="stopSave">stopSave</button>
      <button v-on:click="capturePicture">capturePicture</button>
      <button v-on:click="fullscreen">fullscreen</button>
      <button v-on:click="getOSDTime">getOSDTime</button>
      <button v-on:click="startTalk">startTalk</button>
      <button v-on:click="stopTalk">stopTalk</button>
      <button v-on:click="destroy">destroy</button>
    </div>
  </div>
</template>

<script>
import { EZUIKitPlayer } from "ezuikit-js";
var player = null;

export default {
  name: "Player",
  props: {
    msg: String,
  },
  data() {
    return {
      url: "ezopen://open.ys7.com/BC7799091/1.live",
      accessToken: "at.9uoaxo0k3e5dinq8bretm18e5l37k1l6-26lx1qcvcc-1neesaz-kh9hqvqc3",
      template: "pcLive",
      width: "100%",
      height: 400,
      staticPath: "",
    };
  },
  mounted: () => {
    console.group("mounted 组件挂载完毕状态===============》");
  },
  methods: {
    init() {
      if (player) {
        this.destroy();
      }

      // fetch("https://open.ys7.com/jssdk/ezopen/demo/token")
      //   .then((response) => response.json())
      //   .then((res) => {
      //     var accessToken = res.data.accessToken;
      //   });
      player = new EZUIKitPlayer({
        id: "video-container", // 视频容器ID
        accessToken: this.accessToken,
        url: this.url,
        // simple: 极简版; pcLive: pc直播; pcRec: pc回放; mobileLive: 移动端直播; mobileRec: 移动端回放; security: 安防版; voice: 语音版;
        template: this.template, // 视频模板
        width: this.width,
        height: this.height,
        handleError: (error) => {
          console.error("handleError", error);
        },
        dpr: 2,
        // quality: 1, // 
        // language: "en", // zh | en
        staticPath: this.staticPath, // 如果想使用本地静态资源，请复制根目录下ezuikit_static 到当前目录下， 然后设置该值
        scaleMode: 1, // 默认 0 完全填充窗口，会有拉伸 1: 等比适配 2: 等比完全填充窗口, 超出隐藏 @sine 8.2.0
        env: {
          // https://open.ys7.com/help/1772?h=domain
          // domain默认是 https://open.ys7.com, 如果是私有化部署或海外的环境，请配置对应的domain
          // The default domain is https://open.ys7.com If it is a private deployment or overseas (outside of China) environment, please configure the corresponding domain
          domain: "https://open.ys7.com",
        },
        // staticPath:"https://openstatic.ys7.com/ezuikit_js/v8.1.9/ezuikit_static",
        // 日志打印设置
        loggerOptions: {
          // player.setLoggerOptions(options)
          level: "INFO", // INFO LOG  WARN  ERROR
          name: "ezuikit",
          showTime: true,
        },
        // 视频流的信息回调类型
        /**
         * 打开流信息回调，监听 streamInfoCB 事件
         * 0 : 每次都回调
         * 1 : 只回调一次
         * 注意：会影响性能
         * 默认值 1
         */
        streamInfoCBType: 1,
        // v8.1.10
        // 自定义清晰度 默认 null, 如果有值 sdk 内部不在进行获取, null 默认使用接口获取的清晰度列表, videoLevelList.length === 0 不展示清晰度控件 sdk 内部不在进行获取, videoLevelList.length > 0 展示控件 sdk 内部不在进行获取
        // videoLevelList: [
        //   { level: 1, name: "标清", streamTypeIn: 2 }, // 需要保证支持子码流 (streamTypeIn=2)
        //   { level: 2, name: "高清", streamTypeIn: 1 },
        // ],
        // videoLevelList: [
        //   { level: -1, name: "标清", streamTypeIn: 2 }, // 8.1.17 开始 当 level 的值小于 0时， 不在向设备发送指令，仅根据 streamTypeIn 切换码流 （请保证 streamTypeIn 对应的码流存在）
        //   { level: -2, name: "高清", streamTypeIn: 1 }, // 8.1.17 开始 当 level 的值小于 0时， 不在向设备发送指令，仅根据 streamTypeIn 切换码流 （请保证 streamTypeIn 对应的码流存在）
        // ],
        // 回放列表弹框
        // recListOptions: null,
        // 时间选择器
        // timeOptions: null,
        recordOptions: {
          // 是否开启录制水印， 默认开启
          enabledWatermarkRecord: false,
        },
      });

      // 8.1.x 事件监听
      // player.eventEmitter.on(EZUIKitPlayer.EVENTS.videoInfo, (info) => {
      //   console.warn("eventEmitter videoInfo", info);
      // });
      // 8.2.x 事件监听
      player.on(EZUIKitPlayer.EVENTS.videoInfo, (info) => {
        console.warn("videoInfo", info);
      });

      // 8.1.x 事件监听
      // player.eventEmitter.on(EZUIKitPlayer.EVENTS.audioInfo, (info) => {
      //   console.warn("eventEmitter audioInfo", info);
      // });
      // 8.2.x 事件监听
      player.on(EZUIKitPlayer.EVENTS.audioInfo, (info) => {
        console.warn("audioInfo", info);
      });

      // 首帧渲染成功
      // first frame display
      // 8.1.x 事件监听
      // player.eventEmitter.on(EZUIKitPlayer.EVENTS.firstFrameDisplay, () => {
      //     console.warn("eventEmitter firstFrameDisplay ");
      // });
      // 8.2.x 事件监听
      player.on(EZUIKitPlayer.EVENTS.firstFrameDisplay, () => {
        console.warn("firstFrameDisplay ");
      });

      // 8.1.x 事件监听
      // player.eventEmitter.on(EZUIKitPlayer.EVENTS.streamInfoCB, (info) => {
      //   console.warn("eventEmitter streamInfoCB ", info);
      // });
      // 8.2.x 事件监听
      player.on(EZUIKitPlayer.EVENTS.streamInfoCB, (info) => {
        console.warn("streamInfoCB ", info);
      });

      window.player = player;
    },
    play() {
      if (player) {
        player.play().then((data) => {
          console.log("play 获取 数据", data);
        });
      }
    },
    stop() {
      if (player) {
        player.stop().then((data) => {
          console.log("stop 获取 数据", data);
        });
      }
    },
    getOSDTime() {
      if (player) 
       player.getOSDTime().then((data) => {
        console.log("getOSDTime 获取 数据", data);
      });
    },
    capturePicture() {
      if (player) {
        player.capturePicture(`${new Date().getTime()}`).then((data) => {
          console.log("capturePicture 获取 数据", data);
        });
      }
    },
    openSound() {
      if (player) {
        player.openSound().then((data) => {
          console.log("openSound 获取 数据", data);
        });
      }
    },
    closeSound() {
      if (player) {
        player.closeSound().then((data) => {
          console.log("closeSound 获取 数据", data);
        });
      }
    },
    startSave() {
      if (player) {
        player.startSave(`${new Date().getTime()}`).then((data) => {
          console.log("startSave 获取 数据", data);
        });
      }
    },
    stopSave() {
      if (player) {
        player.stopSave().then((data) => {
          console.log("promise 获取 数据", data);
        });
      }
    },
    startTalk() {
      // 一个页面中只可以有一个对讲
      if (player) {
        player.startTalk();
      }
    },
    stopTalk() {
      if (player) {
        player.stopTalk();
      }
    },
    fullscreen() {
      if (player) player.fullscreen();
    },
    destroy() {
      if (player)  {
        player.destroy().then((data) => {
          console.log("promise 获取 数据", data);
        });
        player = null;
      }
    },
  },
};
</script>

// demos/with-next/src/components/Player.tsx
"use client";

import React, { useCallback, useEffect, useRef } from "react";
import { EZUIKitPlayer } from "ezuikit-js";
import { isMobile } from "./utils";

const Player = () => {
  const player = useRef<any>(null);
  const urlRef = useRef<HTMLInputElement>(null);
  const accessTokenRef = useRef<HTMLInputElement>(null);
  const staticPathRef = useRef<HTMLInputElement>(null);
  const domainRef = useRef<HTMLInputElement>(null);
  const languageRef = useRef<HTMLSelectElement>(null);
  const templateRef = useRef<HTMLSelectElement>(null);

  // 组件卸载时销毁播放器，避免内存泄漏
  useEffect(
    () => () => {
      if (player.current) {
        player.current.destroy();
        player.current = null;
      }
    },
    []
  );

  const initPlayer = useCallback(() => {
    if (document.getElementById("player-container")) {
      let width = 600;
      let height = 400;

      const url = urlRef.current?.value.trim();
      const accessToken = accessTokenRef.current?.value.trim();
      const staticPath = staticPathRef.current?.value.trim() || undefined;
      const domain = domainRef.current?.value.trim() || "https://open.ys7.com";
      const language = languageRef.current?.value.trim();
      const template = templateRef.current?.value.trim();

      if (!url || !accessToken) {
        console.warn("url or accessToken is empty!");
        return;
      }

      if (isMobile()) {
        width = document.documentElement.clientWidth;
        height = (width * 9) / 16;
      }

      if (player.current) {
        player.current.destroy();
        player.current = null;
      }

      if (typeof window !== "undefined") {
        player.current = new EZUIKitPlayer({
          id: "player-container",
          url,
          accessToken,
          width,
          height,
          template,
          staticPath, // 如果想使用本地静态资源，请复制根目录下ezuikit_static 到当前目录下， 然后设置该值
          language, // zh | en
          dpr: 2,
          // quality: 4, // 
          // isCloudRecord: true, // 如果是云录制的播放 需要这个值，是必须的
          scaleMode: 1, // 默认 0 完全填充窗口，会有拉伸 1: 等比适配 2: 等比完全填充窗口, 超出隐藏 @sine 8.2.0
          env: {
            // https://open.ys7.com/help/1772?h=domain
            // domain默认是 https://open.ys7.com, 如果是私有化部署或海外的环境，请配置对应的domain
            // The default domain is https://open.ys7.com If it is a private deployment or overseas (outside of China) environment, please configure the corresponding domain
            domain, // "https://open.ys7.com"
          },
          plugin: ["talk"], // 加载插件，talk-对讲
          // 日志打印设置
          loggerOptions: {
            // player.setLoggerOptions(options)
            level: "INFO", // INFO LOG  WARN  ERROR
            name: "ezuikit",
            showTime: true,
          },
          // 视频流的信息回调类型
          /**
           * 打开流信息回调，监听 streamInfoCB 事件
           * 0 : 每次都回调
           * 1 : 只回调一次
           * 注意：会影响性能
           * 默认值 1
           */
          streamInfoCBType: 1,
          // v8.1.10
          // 自定义清晰度 默认 null, 如果有值 sdk 内部不在进行获取, null 默认使用接口获取的清晰度列表, videoLevelList.length === 0 不展示清晰度控件 sdk 内部不在进行获取, videoLevelList.length > 0 展示控件 sdk 内部不在进行获取
          // videoLevelList: [
          //   { level: 1, name: "标清", streamTypeIn: 2 }, // 需要保证支持子码流 (streamTypeIn=2)
          //   { level: 2, name: "高清", streamTypeIn: 1 },
          // ],
          // videoLevelList: [
          //   { level: -1, name: "标清", streamTypeIn: 2 }, // 8.1.17 开始 当 level 的值小于 0时， 不在向设备发送指令，仅根据 streamTypeIn 切换码流 （请保证 streamTypeIn 对应的码流存在）
          //   { level: -2, name: "高清", streamTypeIn: 1 }, // 8.1.17 开始 当 level 的值小于 0时， 不在向设备发送指令，仅根据 streamTypeIn 切换码流 （请保证 streamTypeIn 对应的码流存在）
          // ],
          // 回放列表弹框
          // recListOptions: null,
          // 时间选择器
          // timeOptions: null,
          recordOptions: {
            // 是否开启录制水印， 默认开启
            enabledWatermarkRecord: false,
          },
        });
      }

      // player.current;

      player.current.on(
        EZUIKitPlayer.EVENTS.videoInfo,
        (info: any) => {
          console.log("videoinfo", info);
        },
      );

      player.current.on(
        EZUIKitPlayer.EVENTS.audioInfo,
        (info: any) => {
          console.log("audioInfo", info);
        },
      );

      // 首帧渲染成功
      // first frame display
      player.current.on(
        EZUIKitPlayer.EVENTS.firstFrameDisplay,
        () => {
          console.log("firstFrameDisplay ");
        },
      );
      player.current.on(
        EZUIKitPlayer.EVENTS.streamInfoCB,
        (info: any) => {
          console.log("streamInfoCB ", info);
        },
      );
    }
  }, []);

  /** 播放 */
  const handlePlay = useCallback(() => {
    if (player.current) {
      player.current.play();
    }
  }, []);

  /** 停止 */
  const handleStop = useCallback(() => {
    if (player.current) {
      player.current.stop();
    }
  }, []);

  /** 开启声音， 默认 0.8, 暂时不可调节， 如要调节请调节系统音量 */
  const handleOpenSound = useCallback(() => {
    if (player.current) {
      player.current.openSound();
    }
  }, []);

  const handleCloseSound = useCallback(() => {
    if (player.current) {
      player.current.closeSound();
    }
  }, []);

  /** 开始录制， 录制需要在播放状态下才可以 */
  const handleStartSave = useCallback(() => {
    if (player.current) {
      player.current.startSave();
    }
  }, []);

  const handleStopSave = useCallback(() => {
    if (player.current) {
      player.current.stopSave();
    }
  }, []);

  /** 抓图/截图 */
  const handleCapturePicture = useCallback(() => {
    if (player.current) {
      player.current.capturePicture();
    }
  }, []);

  /** 全屏 */
  const handleFullscreen = useCallback(() => {
    if (player.current) {
      player.current.fullscreen();
    }
  }, []);

  /** 获取OSD时间 */
  const handleGetOSDTime = useCallback(() => {
    if (player.current) {
      player.current.getOSDTime();
    }
  }, []);

  /**
   * 开始对讲 （仅直播live）
   */
  const handleStartTalk = useCallback(() => {
    if (player.current) {
      player.current.startTalk();
    }
  }, []);

  /**
   * 开始对讲 （仅直播live）
   */
  const handleStopTalk = useCallback(() => {
    if (player.current) {
      player.current.stopTalk();
    }
  }, []);

  const handleDestroy = () => {
    if (player.current) {
      player.current.destroy();
      player.current = null;
    }
  };

  return (
    <div className="player-wrapper">
      <h2>ezopen使用示例 (Example of using ezopen)：</h2>
      <div>
        <div id="player-container"></div>
      </div>
      <div className="form">
        <div className="form-item">
          <label>url</label>
          {/* prettier-ignore */}
          <input ref={urlRef} placeholder="ezopen url" defaultValue="ezopen://open.ys7.com/BC7799091/1.hd.live" />
        </div>
        <div className="form-item">
          <label>accessToken</label>
          {/* prettier-ignore */}
          <input ref={accessTokenRef} placeholder="ezopen accessToken" defaultValue="at.d525oyj8d7bwohb40ssn3266cfq2mwi2-8hgpypehn9-1fafaty-ea2fxbc1" />
        </div>
        <div className="form-item">
          <label>staticPath</label>
          {/* prettier-ignore */}
          {/* https://openstatic.ys7.com/ezuikit_js/v8.1.9/ezuikit_static */}
          <input
            ref={staticPathRef}
            placeholder="ezopen staticPath"
            defaultValue=""
          />
        </div>
        <div className="form-item">
          <label>domain</label>
          {/* prettier-ignore */}
          <input ref={domainRef} placeholder="ezopen env.domain" defaultValue="https://open.ys7.com" />
        </div>
        <div className="form-item">
          <label>language</label>
          <select ref={languageRef} defaultValue="zh" style={{ width: 100 }}>
            <option value="zh">zh</option>
            <option value="en">en</option>
          </select>
        </div>
        <div className="form-item">
          <label>template</label>
          {/* prettier-ignore */}
          <select ref={templateRef} defaultValue="pcLive" style={{ width: 100 }}>
            <option value="simple">simple</option>
            <option value="pcLive">pcLive</option>
            {/* To use the replay theme, please use the replay playback address */}
            <option value="pcRec">pcRec</option>
            {/* <option value="mobileLive">mobileLive</option>
            <option value="mobileRec">mobileRec</option> */}
          </select>
        </div>
      </div>
      <div>
        <button onClick={initPlayer}>初始化(init)</button>
        <button onClick={handleStop}>stop</button>
        <button onClick={handlePlay}>play</button>
        <button onClick={handleOpenSound}>openSound</button>
        <button onClick={handleCloseSound}>closeSound</button>
        <button onClick={handleStartSave}>startSave</button>
        <button onClick={handleStopSave}>stopSave</button>
        <button onClick={handleCapturePicture}>capturePicture</button>
        <button onClick={handleFullscreen}>fullscreen</button>
        <button onClick={handleGetOSDTime}>getOSDTime</button>
        <button onClick={handleStartTalk}>开始对讲(startTalk)</button>
        <button onClick={handleStopTalk}>结束对讲(stopTalk)</button>
        <button onClick={handleDestroy}>destroy</button>
      </div>
    </div>
  );
};

export default Player;
